#!/bin/sh

. ./template.conf

if [ "${gocd_home}" == "" ]; then
    echo "Cannot find required variables"
    exit
fi
echo "Fetching server install"
fetch https://download.gocd.org/binaries/$gocd_version/generic/go-server-$gocd_version.zip -o /root/go-server.zip
echo "Extracting server into '${gocd_home}/${gocd_server_folder}'"
unzip -q -j -d $gocd_home/$gocd_server_folder /root/go-server.zip
echo "Setting ownership on '${gocd_home}/${gocd_server_folder}'"
chown -R $gocd_user_name:$gocd_group_name $gocd_home
echo "Checking plugin folder"
if [ ! -d $gocd_home/$gocd_server_folder/plugins/external/ ]; then
    echo "Creating plugin folder"
    mkdir -p $gocd_home/$gocd_server_folder/plugins/external/
fi
echo "Copying plugins"
cd $gocd_home/$gocd_server_folder/plugins/external/
for plugin in $plugins
do
    echo Fetching basename $plugin
    fetch $plugin -o $gocd_home/$gocd_server_folder/plugins/external/
done
cd -
echo "Done"
